# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling App
      - make build
      - printenv
      - echo "DARK_SKY="$DARK_SKY > ./dist/.env
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "dist/**/*"
    - appspec.yml
